--liquibase formatted sql

--changeset gustavo:08091512
--comment: create table livro
CREATE TABLE LIVRO (
  LIV_ID INT(10) PRIMARY KEY,
  LIV_TITULO VARCHAR(150) NOT NULL,
  LIV_AUTOR VARCHAR(150) NOT NULL,
  LIV_EDITOR VARCHAR(150) NOT NULL,
  LIV_EDICAO VARCHAR(150) NOT NULL,
  LIV_NUM_PAGINAS VARCHAR(20) NOT NULL
);
--rollback DROP TABLE LIVRO;